"""EDE CLI — Typer-based command-line interface.

Commands:
  ede init <name>         Initialize a new EDE project
  ede status              Show project status
  ede task create <desc>  Create a new task
  ede task run [task_id]  Advance the pipeline
  ede confirm <stage>     Confirm a human checkpoint
"""

import logging
import uuid
import typer
from pathlib import Path
from rich.console import Console
from rich.table import Table

from ede.persistence import Persistence
from ede.state_machine import StateMachine
from ede.gate_engine import GateEngine, Gate, GateLevel
from ede.stage_engine import StageEngine, Stage
from ede.llm_adapter import DeepSeekProvider, ChatMessage, thinking_for_phase
from ede.context_engine import ContextEngine, TrustConfig
from ede.self_refinement import SelfRefinement
from ede.reviewer import ReviewerOrchestrator, ReviewReport
from ede.gates.builtin import register_builtin_gates
from ede import tui
from ede.change_visibility import parse_change_summary, parse_change_entries, build_change_summary_prompt
from ede.models import Phase, TaskStatus, GateResult

app = typer.Typer(
    name="ede",
    help="Engineering Discipline Enforcer — DeepSeek-optimized agentic engineering CLI",
)
task_app = typer.Typer(help="Manage EDE tasks")
app.add_typer(task_app, name="task")

logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
console = Console(force_terminal=False, force_interactive=False)

DEFAULT_CONTEXT_YAML = """# EDE project context — auto-generated by `ede init`
# Add project-specific conventions and constraints below.

project:
  type: ""
  frontend: ""
  backend: ""
  database: ""

conventions:
  naming: snake_case
  api_style: rest

constraints: []

history: []
"""


# ── Helpers ──────────────────────────────────────────

def _get_llm():
    import os
    key = os.environ.get("DEEPSEEK_API_KEY", "")
    return DeepSeekProvider(api_key=key) if key else None

def _get_engine() -> StageEngine:
    """Build a StageEngine with default stages and empty gates."""
    ede_dir = Path(".ede")
    if not ede_dir.exists():
        console.print("[red]X[/red] No .ede/ directory found. Run `ede init` first.")
        raise typer.Exit(code=1)

    db = Persistence(str(ede_dir / "state.db"))
    gates = GateEngine()
    trust = TrustConfig.from_yaml(Path(".ede/config.yaml"))
    engine = StageEngine(db, gates, trust)

    # Register all seven stages with empty gates for MVP
    engine.register_stage(Stage(Phase.SPEC, prerequisites=[], gates=[]))
    engine.register_stage(Stage(Phase.DESIGN, prerequisites=[], gates=[]))
    engine.register_stage(Stage(Phase.PLAN, prerequisites=[], gates=[]))
    llm = _get_llm()
    ctx_engine = ContextEngine(".")
    def _make_run_fn(phase):
        def _run(task_id, p):
            if llm is None:
                return
            import asyncio
            ctx = ctx_engine.resolve()
            sp = DeepSeekProvider.build_system_prompt(ctx)
            msgs = [ChatMessage(role="system", content=sp),
                    ChatMessage(role="user", content=f"Phase: {phase.value}, task: {task_id}")]
            try:
                loop = asyncio.get_event_loop()
            except RuntimeError:
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
            result = loop.run_until_complete(llm.chat(msgs, thinking_budget=thinking_for_phase(phase)))
            console.print(f"  [dim]LLM response: {result.output_tokens} tokens[/dim]")
            # Parse and persist change log + change entries
            if result.content and "Change Summary" in result.content:
                ch = parse_change_summary(result.content)
                ch.task_id = task_id
                try:
                    ede_dir = __import__('pathlib').Path('.ede')
                    if ede_dir.exists():
                        pdb = Persistence(str(ede_dir / 'state.db'))
                        pdb.insert_change_log(ch)
                        console.print(f"  [dim]ChangeLog saved: {ch.intent_group.value} / {ch.risk_label.value}[/dim]")
                        # Parse and persist per-file change entries
                        entries = parse_change_entries(result.content, ch.change_id)
                        for entry in entries:
                            pdb.insert_change_entry(entry)
                        if entries:
                            console.print(f"  [dim]ChangeEntries saved: {len(entries)} entries[/dim]")
                except Exception:
                    logging.getLogger("ede.cli").warning("Failed to persist ChangeLog/Entries", exc_info=True)
        return _run
    # Register builtin gates and attach to stages
    register_builtin_gates(gates, ".")
    engine.register_stage(Stage(Phase.CODE, prerequisites=[], gates=["lint", "test"], run_fn=_make_run_fn(Phase.CODE)))
    engine.register_stage(Stage(Phase.TEST, prerequisites=[], gates=["test", "coverage"], run_fn=_make_run_fn(Phase.TEST)))
    engine.register_stage(Stage(Phase.REVIEW, prerequisites=[], gates=[], run_fn=_make_run_fn(Phase.REVIEW)))
    engine.register_stage(Stage(Phase.MERGE, prerequisites=[], gates=[], run_fn=_make_run_fn(Phase.MERGE)))

    # Inject accuracy reviewer for post-code checks
    llm = _get_llm()
    if llm is not None:
        reviewer = ReviewerOrchestrator(llm)
        engine.set_reviewer(reviewer)

    return engine


# ── Root commands ────────────────────────────────────

@app.command()
def init(name: str) -> None:
    """Initialize a new EDE project in the current directory."""
    project_id = str(uuid.uuid4())[:8]
    ede_dir = Path(".ede")
    db_path = ede_dir / "state.db"
    context_path = ede_dir / "context.yaml"
    audit_path = ede_dir / "ede_audit.log"

    try:
        ede_dir.mkdir(parents=True, exist_ok=False)
    except FileExistsError:
        console.print("[yellow]!![/yellow] .ede/ already exists in this directory.")
        raise typer.Exit(code=1)

    try:
        db = Persistence(str(db_path))
        db.init_db()
    except Exception as e:
        console.print(f"[red]X[/red] Failed to initialize database: {e}")
        raise typer.Exit(code=1)

    context_path.write_text(DEFAULT_CONTEXT_YAML, encoding="utf-8")
    audit_path.write_text(
        f"# EDE Audit Log — project {name} ({project_id})\n"
        f"# Created: {__import__('datetime').datetime.now().isoformat()}\n\n"
    )
    db.insert_project(project_id, name)

    # Generate config.yaml with default trust tier
    config_path = ede_dir / "config.yaml"
    config_path.write_text("""# EDE project config — auto-generated by `ede init`
# Trust tier: T0=conservative, T1=assisted(default), T2=autonomous, T3=full auto
# See spec §8 for details.

trust:
  tier: T1
  overrides: {}
    # merge: T0  # uncomment to require manual merge confirmation
""", encoding="utf-8")

    tui.render_init_summary(project_id, name, str(db_path), str(context_path), str(audit_path))


@app.command()
def status() -> None:
    """Show current project status."""
    ede_dir = Path(".ede")
    if not ede_dir.exists():
        console.print("[red]X[/red] No .ede/ directory found. Run `ede init` first.")
        raise typer.Exit(code=1)

    db = Persistence(str(ede_dir / "state.db"))
    tables = db.get_tables()
    if not tables:
        console.print("[yellow]!![/yellow] Database is empty.")
        return

    table = Table(title="EDE Status")
    table.add_column("Table", style="cyan")
    table.add_column("Rows", justify="right")
    for t in tables:
        table.add_row(t, str(db.table_count(t)))
    console.print(table)


# ── Task commands ────────────────────────────────────

@task_app.command("create")
def task_create(
    description: str,
    start_at: str = typer.Option("spec", "--start-at", "-s",
        help="Start at phase: spec, design, plan, code, test, review, merge"),
) -> None:
    """Create a new task, optionally starting from a later phase."""
    valid = {"spec", "design", "plan", "code", "test", "review", "merge"}
    if start_at not in valid:
        console.print(f"[red]X[/red] Invalid --start-at value: {start_at}. Valid: {', '.join(sorted(valid))}")
        raise typer.Exit(code=1)

    engine = _get_engine()
    task_id = str(uuid.uuid4())[:8]
    project_id = _get_first_project_id(engine.db)
    engine.db.create_task(task_id, project_id, description, start_phase=start_at)

    # Auto-complete audit trail for skipped phases
    phases = ["spec", "design", "plan", "code", "test", "review", "merge"]
    skipped = [p for p in phases if phases.index(p) < phases.index(start_at)]
    for p in skipped:
        engine.db.write_audit(task_id, "phase_skipped", f"Skipped {p} (started at {start_at})")

    tui.render_task_created(task_id, description)
    console.print(f"  Starting at: [bold]{start_at}[/bold]{' (skipped '+', '.join(skipped)+')' if skipped else ''}")


@task_app.command("run")
def task_run(task_id: str = "") -> None:
    """Advance the pipeline. Uses the most recent task if task_id not given."""
    engine = _get_engine()
    if not task_id:
        task = engine.db.get_first_task()
        if task is None:
            console.print("[red]X[/red] No tasks found. Run `ede task create` first.")
            raise typer.Exit(code=1)
        task_id = task["task_id"]

    task = engine.db.get_task(task_id)
    if task is None:
        console.print(f"[red]X[/red] Task {task_id} not found.")
        raise typer.Exit(code=1)

    result = engine.advance(task_id)
    tui.render_pipeline_result(result)


@app.command("confirm")
def confirm(stage: str) -> None:
    """Confirm a human checkpoint (spec, design, or plan)."""
    engine = _get_engine()
    task = engine.db.get_first_task()
    if task is None:
        console.print("[red]X[/red] No tasks found.")
        raise typer.Exit(code=1)

    result = engine.confirm(task["task_id"], stage)
    tui.render_pipeline_result(result)


# ── Helpers ──────────────────────────────────────────

def _get_first_project_id(db: Persistence) -> str:
    """Get the first project id from the database."""
    tables = db.get_tables()
    if "project" in tables:
        with __import__('sqlite3').connect(db.db_path) as conn:
            conn.row_factory = __import__('sqlite3').Row
            row = conn.execute("SELECT project_id FROM project LIMIT 1").fetchone()
            return row["project_id"] if row else "default"
    return "default"






@app.command("dashboard")
def dashboard() -> None:
    """Show interactive project dashboard."""
    ede_dir = __import__("pathlib").Path(".ede")
    if not ede_dir.exists():
        tui.console.print("[red]X[/red] No .ede/ directory found.")
        raise typer.Exit(code=1)

    db = Persistence(str(ede_dir / "state.db"))
    task = db.get_first_task()
    if task is None:
        tui.console.print("[yellow]!![/yellow] No tasks found.")
        return

    # Gather checkpoints and audit logs
    checkpoints = []
    audit_logs = []
    try:
        # Query checkpoints
        import sqlite3
        conn = sqlite3.connect(str(ede_dir / "state.db"))
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT stage, status, confirmed_at FROM checkpoint WHERE task_id=? ORDER BY id",
            (task["task_id"],),
        ).fetchall()
        checkpoints = [dict(r) for r in rows]
        conn.close()
    except Exception:
        logging.getLogger("ede.cli").warning("Failed to query checkpoints", exc_info=True)

    audit_logs = db.get_audit_logs(task["task_id"])

    tui.render_status_dashboard(task, checkpoints, audit_logs)

@app.command("refine")
def refine() -> None:
    """Analyze audit logs and suggest context.yaml improvements."""
    ede_dir = __import__("pathlib").Path(".ede")
    if not ede_dir.exists():
        console.print("[red]X[/red] No .ede/ directory found.")
        raise typer.Exit(code=1)

    db = Persistence(str(ede_dir / "state.db"))
    task = db.get_first_task()
    if task is None:
        console.print("[yellow]!![/yellow] No tasks to analyze.")
        return

    logs = db.get_audit_logs(task["task_id"])
    if not logs:
        console.print("[yellow]!![/yellow] No audit logs found.")
        return

    sr_engine = SelfRefinement(".")
    suggestions = sr_engine.analyze(logs)
    console.print(sr_engine.get_suggestions_summary(suggestions))

    if suggestions:
        result = sr_engine.apply(suggestions)
        console.print(f"  Updated: {result['updated']}, Skipped: {result['skipped']}")


if __name__ == "__main__":
    app()
